name: Rilog lib

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build --workspace=@rilog-development/rilog-lib

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run build --workspace=@rilog-development/rilog-lib
      - run: npm publish --workspace=@rilog-development/rilog-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
